#!/usr/bin/sh
#
# Build the given target.
#
# Author:   Alastair Hughes
# Contact:  < hobbitalastair at yandex dot com >

source "$(dirname "$0")/../../libmain.sh"
source "$(dirname "$0")/../../libtarget.sh"

# Building is essentially meaningless for a target; instead, just print a
# message saying that the target has been met.
if "${DEBUG}"; then
    message debug "Met ${target}"
fi

