#!/usr/bin/bash
#
# Extract the dependencies for the given target.
#
# Author:   Alastair Hughes
# Contact:  < hobbitalastair at yandex dot com >

source "$(dirname "$0")/../../libmain.sh"
source "$(dirname "$0")/../../libtarget.sh"

path="${configdir}/src/${target}"
exists "${path}"

cat "${path}" || exit $?
