#!/usr/bin/sh
#
# Print the current state of the given target.
# 
# Author:   Alastair Hughes
# Contact:  < hobbitalastair at yandex dot com >

configdir="$1"
target="$2"

path="${configdir}/src/${target}"

if [ ! -e "${path}" ]; then
    echo "No such target '${target}'!" > /dev/stderr
    exit 1
fi

md5sum "${configdir}/src/${target}" | cut -d' ' -f1

