#!/usr/bin/bash
#
# Print the current state of the given target.
# 
# Author:   Alastair Hughes
# Contact:  < hobbitalastair at yandex dot com >

source "$(dirname "$0")/../../lib/libmain.sh"
source "$(dirname "$0")/../../lib/libtarget.sh"

path="${configdir}/src/${target}"
sum_file "${path}" || exit $?
