#!/usr/bin/bash
#
# Extract the dependencies for the given path.
#
# Author:   Alastair Hughes
# Contact:  < hobbitalastair at yandex dot com >

source "$(dirname "$0")/../../lib/libmain.sh"
source "$(dirname "$0")/../../lib/libtarget.sh"

if [ "${name:0:1}" != "/" ]; then
    path="${configdir}/${name}"
else
    path="${name}"
fi

exists "${path}" || exit "$?"
