#!/usr/bin/bash
#
# Print the current state of the given path.
# 
# Author:   Alastair Hughes
# Contact:  < hobbitalastair at yandex dot com >

source "$(dirname "$0")/../../lib/libmain.sh"
source "$(dirname "$0")/../../lib/libtarget.sh"

if [ "${name:0:1}" != "/" ]; then
    path="${configdir}/${name}"
else
    path="${name}"
fi

exists "${path}" || exit "$?"
# We sum the file, minus blank lines and comments.
# This prevents excessive rebuilds.
sed -n -e 's:#.*::' -e '/^..*$/p' < "${path}" | md5sum | cut -d' ' -f1
