#!/usr/bin/bash
#
# Print the current state of the given path.
# 
# Author:   Alastair Hughes
# Contact:  < hobbitalastair at yandex dot com >

source "$(dirname "$0")/../../libmain.sh"
source "$(dirname "$0")/../../libtarget.sh"

if [ "${name:0:1}" != "/" ]; then
    path="${configdir}/${name}"
else
    path="${name}"
fi

exists "${path}" || exit "$?"
sum_file "${path}" || exit "$?"
