#!/usr/bin/bash
#
# Extract the dependencies for the given target.
#
# Author:   Alastair Hughes
# Contact:  < hobbitalastair at yandex dot com >

source "$(dirname "$0")/../../lib/libmain.sh"
source "$(dirname "$0")/../../lib/libpackage.sh"
source "$(dirname "$0")/../../lib/libtarget.sh"
loadrepoconf "${configdir}"

# Special case host packages.
[ "${name%%/*}" == "host" ] && exit

# We depend on some extra files.
printf "srctar/%s\n" "${name}"
printf "srcinfo/%s\n" "${name}"
printf "path/config\n"
printf "path/src/%s/repo.conf\n" "${name%%/*}"
makepkgconf="src/${name%%/*}/makepkg.conf"
if [ -f "${configdir}/${makepkgconf}" ]; then
    printf 'path/%s\n' "${makepkgconf}"
fi

# We also depend on some other packages.
path="${configdir}/src/${name}/PKGBUILD"
exists "${path}" || exit "$?"
# Extract the deps.
deps="$(gendeps "${configdir}" "${name}" \
    "$(dirname "$0")/../../scripts/lsdeps.sh")" || \
    exit 1
# Turn the deps into actual paths.
pkgpaths="$(printf "%s\n" "${deps}" | \
    findpkgdeps "${configdir}" "${name%%/*}")" || \
    error "$?" "Failed to find the package dirs!"
printf "%s\n" "${pkgpaths}" | cut -d' ' -f2-
