#!/usr/bin/bash

source "$(dirname "$0")/../../lib/libmain.sh"
source "$(dirname "$0")/../../lib/libtarget.sh"
source "$(dirname "$0")/../../lib/libpackage.sh"
loadrepoconf "${configdir}"

# Special case host packages.
if [ "${name%%/*}" == "host" ]; then
    # For speed reasons, just print 'na'.
    # We also have issues if the given package name contains a version
    # requirement.
    printf 'na'
    exit
fi

# We take the checksum of the PKGBUILD, which should change if anything else
# does.
path="${configdir}/src/${name}/PKGBUILD"
exists "${path}"
sum="$(sum_file "${path}")" || exit $?

message debug "Checking ${path}"
# We also need to take the sum of the built package.
if [ ! -f "${configdir}/src/${name}/.SRCINFO" ]; then
    # Bail early if there is no .SRCINFO.
    printf "old"
    exit 0
fi
packages="$(pkgdirpackages "${configdir}" "${name}")" || \
    error "$?" "Failed to generate a list of packages for '${name}'!"
for pkg in ${packages}; do
    message debug "Trying to sum ${configdir}/pkgs/${pkg}"
    newsum="$(sum_file "${configdir}/pkgs/${pkg}")"
    if [ "${newsum}" == "old" ]; then
        # Bail if the package is old.
        printf "old"
        exit 0
    fi
    sum+=" ${newsum}"
done

printf "${sum}"
