#!/usr/bin/bash
#
# Build the given target.
#
# Author:   Alastair Hughes
# Contact:  < hobbitalastair at yandex dot com >

source "$(dirname "$0")/../../libmain.sh"
source "$(dirname "$0")/../../libtarget.sh"
source "$(dirname "$0")/../../libpackage.sh"

configdir="$(realpath "${configdir}")"
path="${configdir}/src/${name}"
exists "${path}/PKGBUILD"
pushd "${path}" || exit 1
makepkg -f -m --allsource --config /dev/stdin << EOF
    source "${configdir}/src/${name%%/*}/makepkg.conf"
    SRCPKGDEST="${configdir}/srctar"
    SRCEXT='${SRCEXT}'
EOF
exit "$?"
