#!/usr/bin/sh
#
# Build the given target.
#
# Author:   Alastair Hughes
# Contact:  < hobbitalastair at yandex dot com >

source "$(dirname "$0")/../../libmain.sh"
source "$(dirname "$0")/../../libtarget.sh"

exists "${configdir}/src/${name}/PKGBUILD"

# Create the makepkg config file.
config="$(mktemp "${TMPDIR:-/tmp}/mksrctar.XXXXXXXX")"
trap "rm '${config}'" EXIT
cat > "${config}" << EOF
source ../makepkg.conf
source /etc/makepkg.conf
SRCPKGDEST="$(realpath "${configdir}")/srctar"
EOF

# Run makepkg.
pushd "${configdir}/src/${name}" > /dev/null
makepkg -f -m --config "${config}" --allsource 2> /dev/null || \
    exit "$?"
