#!/usr/bin/bash
#
# Build the given target.
#
# Author:   Alastair Hughes
# Contact:  < hobbitalastair at yandex dot com >

source "$(dirname "$0")/../../libmain.sh"
source "$(dirname "$0")/../../libtarget.sh"
source "$(dirname "$0")/../../libpackage.sh"
read_config

path="${configdir}/src/${name}"
exists "${path}/PKGBUILD"
pushd "${path}" || exit 1
# Create the config file.
conf="$(mktemp "${TMPDIR:-/tmp}/makepkg-conf.XXXXXXXX")" || \
    error 1 "Failed to create a temporary file for '${target}'!"
trap "rm -f '${conf}'" EXIT
cat /etc/makepkg.conf >> "${conf}"
genmakepkgconf "${configdir}" "${name}" >> "${conf}"
printf 'SRCPKGDEST="%s/srctar"\n' "${configdir}" >> "${conf}"
# Make the source tarball.
makepkg -f --allsource --config "${conf}"
exit "$?"
