#!/usr/bin/bash
source "$(dirname "$0")/../../libmain.sh"
source "$(dirname "$0")/../../libtarget.sh"
source "$(dirname "$0")/../../libpackage.sh"

exists "${configdir}/src/${name}/PKGBUILD"
srctar="$(pkgdirsrctar "${configdir}" "${name}")"
if [ "$?" -eq 2 ]; then
    # Bail if the .SRCINFO does not exist at this time.
    # TODO: This may be wrong - there may be an up-to-date tarball, but no
    #       .SRCINFO. Is the build system smart enough to figure this out?
    echo 'old'
    exit
fi
sum_file "${configdir}/srctar/${srctar}" || exit "$?"
