#!/usr/bin/sh
#
# Build the given target.
#
# Author:   Alastair Hughes
# Contact:  < hobbitalastair at yandex dot com >

source "$(dirname "$0")/../../libmain.sh"
source "$(dirname "$0")/../../libtarget.sh"

# Actions do not actually need rebuilding.
exists "${configdir}/src/${target}" || exit 1
