#!/usr/bin/bash
#
# Build the given target.
#
# Author:   Alastair Hughes
# Contact:  < hobbitalastair at yandex dot com >

source "$(dirname "$0")/../../libmain.sh"
source "$(dirname "$0")/../../libtarget.sh"
source "$(dirname "$0")/../../libpackage.sh"

configdir="$(realpath "${configdir}")"
path="${configdir}/src/${name}"
exists "${path}/PKGBUILD"
# TODO: We use -A here; this is a bug in makepkg...
pushd "${path}" || exit 1
makepkg -A --printsrcinfo --config /dev/stdin > "${path}/.SRCINFO" << EOF
    source "/etc/makepkg.conf"
    source "${configdir}/src/config.sh"
    source '${configdir}/src/${name%%/*}/makepkg.conf'
EOF
exit "$?"
