#!/usr/bin/bash
#
# Build the given target.
#
# Author:   Alastair Hughes
# Contact:  < hobbitalastair at yandex dot com >

source "$(dirname "$0")/../../libmain.sh"
source "$(dirname "$0")/../../libtarget.sh"
source "$(dirname "$0")/../../libpackage.sh"

path="${configdir}/src/${name}"
exists "${path}/PKGBUILD"
# TODO: We use -A here; this is a bug in makepkg...
LOGFILE=".SRCINFO" \
    callmakepkg "${configdir}" "${name%%/*}" "${path}" -A --printsrcinfo || \
    exit "$?"
