#!/usr/bin/bash
#
# Build the given target.
#
# Author:   Alastair Hughes
# Contact:  < hobbitalastair at yandex dot com >

source "$(dirname "$0")/../../libmain.sh"
source "$(dirname "$0")/../../libtarget.sh"
source "$(dirname "$0")/../../libpackage.sh"

exists "${configdir}/src/${name}/PKGBUILD"
callmakepkg "${configdir}" "${prefix}" "${name}" -A \
    --printsrcinfo > .SRCINFO || exit "$?"
